# Generated by Django 4.2.26 on 2025-11-23 23:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="Item identifier", max_length=100
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=200)),
                ("description", models.TextField(help_text="Detailed description")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("consumable", "Consumable"),
                            ("quest", "Quest Item"),
                            ("currency", "Currency"),
                            ("container", "Container"),
                            ("tool", "Tool"),
                            ("misc", "Miscellaneous"),
                        ],
                        default="misc",
                        help_text="Type of item",
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight in units",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        help_text="Base value in currency",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_takeable",
                    models.BooleanField(default=True, help_text="Can be picked up"),
                ),
                (
                    "is_droppable",
                    models.BooleanField(default=True, help_text="Can be dropped"),
                ),
                (
                    "is_unique",
                    models.BooleanField(
                        default=False, help_text="Only one can exist per player"
                    ),
                ),
                (
                    "is_quest_item",
                    models.BooleanField(
                        default=False, help_text="Required for a quest"
                    ),
                ),
                (
                    "equipment_slot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("head", "Head"),
                            ("neck", "Neck"),
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("arms", "Arms"),
                            ("hands", "Hands"),
                            ("waist", "Waist"),
                            ("legs", "Legs"),
                            ("feet", "Feet"),
                            ("finger1", "Finger 1"),
                            ("finger2", "Finger 2"),
                            ("main_hand", "Main Hand"),
                            ("off_hand", "Off Hand"),
                            ("two_hand", "Two Handed"),
                        ],
                        help_text="Equipment slot if this is wearable",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_equipped",
                    models.BooleanField(default=False, help_text="Currently equipped"),
                ),
                (
                    "required_level",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum level to use",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "stat_modifiers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stat bonuses {'strength': 5, 'defense': 10, ...}",
                    ),
                ),
                (
                    "uses_remaining",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of uses left (for consumables)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum uses",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "effect",
                    models.JSONField(
                        blank=True,
                        help_text="Effect when used {'type': 'heal', 'amount': 50}",
                        null=True,
                    ),
                ),
                (
                    "container_capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Items it can hold if it's a container",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="NPC identifier", max_length=100
                    ),
                ),
                ("name", models.CharField(help_text="NPC name", max_length=200)),
                ("description", models.TextField(help_text="NPC description")),
                (
                    "ai_type",
                    models.CharField(
                        choices=[
                            ("passive", "Passive"),
                            ("friendly", "Friendly"),
                            ("neutral", "Neutral"),
                            ("aggressive", "Aggressive"),
                            ("merchant", "Merchant"),
                            ("quest_giver", "Quest Giver"),
                            ("guard", "Guard"),
                            ("trainer", "Trainer"),
                        ],
                        default="passive",
                        help_text="AI behavior type",
                        max_length=50,
                    ),
                ),
                (
                    "dialogue_tree",
                    models.JSONField(
                        blank=True,
                        help_text="Conversation options and responses",
                        null=True,
                    ),
                ),
                (
                    "greeting_message",
                    models.CharField(
                        blank=True,
                        help_text="Message when player first approaches",
                        max_length=500,
                    ),
                ),
                (
                    "patrol_route",
                    models.JSONField(
                        blank=True, help_text="List of room keys to patrol", null=True
                    ),
                ),
                (
                    "wanders",
                    models.BooleanField(
                        default=False, help_text="Whether NPC wanders randomly"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="NPC level",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "health",
                    models.IntegerField(
                        default=100,
                        help_text="Current health",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_health",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum health",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "damage",
                    models.IntegerField(
                        default=10,
                        help_text="Base damage",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "defense",
                    models.IntegerField(
                        default=5,
                        help_text="Defense rating",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loot_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Items that can drop [{'item_key': 'sword', 'chance': 0.5}, ...]",
                    ),
                ),
                (
                    "currency_drop",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Currency drop range {'min': 10, 'max': 50}",
                    ),
                ),
                (
                    "experience_reward",
                    models.IntegerField(
                        default=0,
                        help_text="Experience given when defeated",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sells_items",
                    models.BooleanField(
                        default=False, help_text="Whether this NPC sells items"
                    ),
                ),
                (
                    "buys_items",
                    models.BooleanField(
                        default=False, help_text="Whether this NPC buys items"
                    ),
                ),
                (
                    "price_modifier",
                    models.FloatField(
                        default=1.0,
                        help_text="Price multiplier for buying/selling",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "respawn_time",
                    models.IntegerField(
                        default=300,
                        help_text="Respawn time in seconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_alive",
                    models.BooleanField(default=True, help_text="Whether NPC is alive"),
                ),
                (
                    "death_time",
                    models.DateTimeField(
                        blank=True, help_text="When NPC died", null=True
                    ),
                ),
                (
                    "is_unique",
                    models.BooleanField(
                        default=False, help_text="Only one instance exists"
                    ),
                ),
                (
                    "is_attackable",
                    models.BooleanField(
                        default=True, help_text="Can be attacked by players"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom attributes and flags",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NPC",
                "verbose_name_plural": "NPCs",
                "ordering": ["location", "name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        db_index=True,
                        help_text="In-game character name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="A mysterious adventurer.",
                        help_text="Character description",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="Character level",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "experience",
                    models.BigIntegerField(
                        default=0,
                        help_text="Experience points",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "health",
                    models.IntegerField(
                        default=100,
                        help_text="Current health points",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_health",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum health points",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "mana",
                    models.IntegerField(
                        default=100,
                        help_text="Current mana points",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_mana",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum mana points",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=10,
                        help_text="Physical power",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "dexterity",
                    models.IntegerField(
                        default=10,
                        help_text="Agility and reflexes",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "intelligence",
                    models.IntegerField(
                        default=10,
                        help_text="Mental acuity and magical power",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "constitution",
                    models.IntegerField(
                        default=10,
                        help_text="Endurance and vitality",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("standing", "Standing"),
                            ("sitting", "Sitting"),
                            ("lying", "Lying Down"),
                            ("sleeping", "Sleeping"),
                            ("dead", "Dead"),
                        ],
                        default="standing",
                        help_text="Character position/posture",
                        max_length=20,
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, help_text="Whether player is currently connected"
                    ),
                ),
                (
                    "inventory_size",
                    models.IntegerField(
                        default=20,
                        help_text="Maximum inventory capacity",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "currency",
                    models.BigIntegerField(
                        default=0,
                        help_text="In-game currency",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When character was created"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, help_text="Last login time", null=True
                    ),
                ),
                (
                    "last_action",
                    models.DateTimeField(
                        blank=True, help_text="Last action/command time", null=True
                    ),
                ),
                (
                    "total_playtime",
                    models.DurationField(
                        default=datetime.timedelta, help_text="Total time played"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom attributes and flags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique zone identifier (e.g., 'newbie_town')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the zone", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Zone description and lore"),
                ),
                (
                    "level_min",
                    models.IntegerField(
                        default=1, help_text="Recommended minimum level"
                    ),
                ),
                (
                    "level_max",
                    models.IntegerField(
                        default=100, help_text="Recommended maximum level"
                    ),
                ),
                (
                    "is_safe",
                    models.BooleanField(
                        default=False, help_text="No combat allowed in entire zone"
                    ),
                ),
                (
                    "is_pvp",
                    models.BooleanField(
                        default=False, help_text="Player vs Player combat allowed"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hidden from zone lists"
                    ),
                ),
                (
                    "is_instanced",
                    models.BooleanField(
                        default=False, help_text="Each party gets their own copy"
                    ),
                ),
                (
                    "climate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("temperate", "Temperate"),
                            ("tropical", "Tropical"),
                            ("arctic", "Arctic"),
                            ("desert", "Desert"),
                            ("underground", "Underground"),
                            ("magical", "Magical"),
                        ],
                        help_text="Zone climate/environment",
                        max_length=50,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Custom zone attributes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zones_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["level_min", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique room identifier (e.g., 'town_square')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the room", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the room"),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True,
                        help_text="3D coordinates {'x': 0, 'y': 0, 'z': 0}",
                        null=True,
                    ),
                ),
                (
                    "is_dark",
                    models.BooleanField(
                        default=False,
                        help_text="Whether room is dark (requires light source)",
                    ),
                ),
                (
                    "is_safe",
                    models.BooleanField(
                        default=False, help_text="No combat allowed in this room"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, help_text="Limited access room"),
                ),
                (
                    "is_indoors",
                    models.BooleanField(
                        default=False, help_text="Indoor vs outdoor room"
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum number of players allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic room state (puzzle states, flags, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone this room belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="game.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["zone", "key"],
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique quest identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Quest title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Quest description and story"),
                ),
                (
                    "required_level",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum level to accept quest",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        help_text="\n        Quest objectives in format:\n        [\n            {'type': 'kill', 'target': 'goblin', 'count': 10},\n            {'type': 'collect', 'item': 'herb', 'count': 5},\n            {'type': 'talk_to', 'npc': 'elder'},\n            {'type': 'visit', 'room': 'ancient_temple'},\n        ]\n        "
                    ),
                ),
                (
                    "experience_reward",
                    models.IntegerField(
                        default=0,
                        help_text="Experience points awarded",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency_reward",
                    models.IntegerField(
                        default=0,
                        help_text="Currency awarded",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_repeatable",
                    models.BooleanField(default=False, help_text="Can be repeated"),
                ),
                (
                    "cooldown_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours before quest can be repeated",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Time limit to complete quest (minutes)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_rewards",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Items awarded upon completion",
                        related_name="quest_rewards",
                        to="game.item",
                    ),
                ),
                (
                    "prerequisite_quests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Quests that must be completed first",
                        to="game.quest",
                    ),
                ),
                (
                    "quest_giver",
                    models.ForeignKey(
                        help_text="NPC who gives this quest",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests_given",
                        to="game.npc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest",
                "verbose_name_plural": "Quests",
                "ordering": ["required_level", "title"],
            },
        ),
        migrations.CreateModel(
            name="PlayerQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        help_text="Quest status",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.JSONField(
                        default=dict,
                        help_text="\n        Tracks objective completion:\n        {\n            '0': {'current': 5, 'required': 10},  # Objective index\n            '1': {'current': 3, 'required': 5},\n        }\n        ",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When quest was accepted"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When quest was completed", null=True
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quest deadline (if time-limited)",
                        null=True,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Player undertaking the quest",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="game.player",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        help_text="The quest",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_quests",
                        to="game.quest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Quest",
                "verbose_name_plural": "Player Quests",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="home",
            field=models.ForeignKey(
                blank=True,
                help_text="Home/respawn location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players_home",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current room location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players_here",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                help_text="User account for this player",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="npc",
            name="home_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Home/spawn location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="npcs_home",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="npc",
            name="location",
            field=models.ForeignKey(
                help_text="Current room",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="npcs_here",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="owner_npc",
            field=models.ForeignKey(
                blank=True,
                help_text="NPC who owns this item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="game.npc",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="owner_player",
            field=models.ForeignKey(
                blank=True,
                help_text="Player who owns this item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Room where item is located",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_here",
                to="game.room",
            ),
        ),
        migrations.CreateModel(
            name="Exit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("north", "North"),
                            ("south", "South"),
                            ("east", "East"),
                            ("west", "West"),
                            ("northeast", "Northeast"),
                            ("northwest", "Northwest"),
                            ("southeast", "Southeast"),
                            ("southwest", "Southwest"),
                            ("up", "Up"),
                            ("down", "Down"),
                            ("in", "In"),
                            ("out", "Out"),
                        ],
                        help_text="Direction of the exit",
                        max_length=20,
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom exit name (e.g., 'door', 'portal')",
                        max_length=100,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Whether exit is locked"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hidden exit (requires discovery)"
                    ),
                ),
                (
                    "is_one_way",
                    models.BooleanField(
                        default=False, help_text="Exit only works in one direction"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether exit is currently usable"
                    ),
                ),
                (
                    "message_enter",
                    models.CharField(
                        blank=True,
                        help_text="Message shown when entering (e.g., 'You walk north.')",
                        max_length=200,
                    ),
                ),
                (
                    "message_leave",
                    models.CharField(
                        blank=True,
                        help_text="Message shown to others when leaving",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        help_text="Room this exit leads to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exits_in",
                        to="game.room",
                    ),
                ),
                (
                    "required_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item required to unlock this exit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks_exits",
                        to="game.item",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Room this exit leads from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exits_out",
                        to="game.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exit",
                "verbose_name_plural": "Exits",
                "ordering": ["source", "direction"],
            },
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["key"], name="game_zone_key_9de6dd_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["level_min", "level_max"], name="game_zone_level_m_ef0472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["key"], name="game_room_key_a9c0ae_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["zone"], name="game_room_zone_id_493101_idx"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(fields=["key"], name="game_quest_key_94b25d_idx"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(
                fields=["required_level"], name="game_quest_require_cd0c12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerquest",
            index=models.Index(
                fields=["player", "status"], name="game_player_player__16d492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerquest",
            index=models.Index(
                fields=["quest", "status"], name="game_player_quest_i_9956e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerquest",
            unique_together={("player", "quest", "status")},
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["character_name"], name="game_player_charact_f7affa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["is_online"], name="game_player_is_onli_e3ba1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["level"], name="game_player_level_86a0f4_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["key"], name="game_npc_key_a3b9df_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["location"], name="game_npc_locatio_f5d861_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["is_alive"], name="game_npc_is_aliv_0c2b7c_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["ai_type"], name="game_npc_ai_type_4e4600_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["key"], name="game_item_key_4deae7_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_type"], name="game_item_item_ty_9e9535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["owner_player"], name="game_item_owner_p_bff1c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["room"], name="game_item_room_id_8a2877_idx"),
        ),
        migrations.AddIndex(
            model_name="exit",
            index=models.Index(
                fields=["source", "direction"], name="game_exit_source__477f48_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exit",
            unique_together={("source", "direction")},
        ),
    ]
