# Generated by Django 4.2.26 on 2025-11-24 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(help_text="Squad designation (e.g., 'Alpha Squad', 'Bravo Squad')", max_length=100)),
                ('callsign', models.CharField(blank=True, help_text="Radio callsign (e.g., 'Havoc', 'Reaper')", max_length=50)),
                ('morale', models.IntegerField(default=100, help_text='Squad morale (affects performance)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cohesion', models.IntegerField(default=50, help_text='Squad cohesion (improves with battles fought together)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_kills', models.IntegerField(default=0, help_text='Total enemy kills by squad', validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_completed', models.IntegerField(default=0, help_text='Number of missions completed', validators=[django.core.validators.MinValueValidator(0)])),
                ('ammunition_556mm', models.IntegerField(default=1000, help_text='5.56mm rounds for M4A1 carbines', validators=[django.core.validators.MinValueValidator(0)])),
                ('ammunition_556mm_belt', models.IntegerField(default=600, help_text='5.56mm belt ammunition for M249 LMGs', validators=[django.core.validators.MinValueValidator(0)])),
                ('grenades_frag', models.IntegerField(default=20, help_text='Fragmentation grenades', validators=[django.core.validators.MinValueValidator(0)])),
                ('grenades_40mm', models.IntegerField(default=30, help_text='40mm grenades for M320 launchers', validators=[django.core.validators.MinValueValidator(0)])),
                ('medkits', models.IntegerField(default=10, help_text='First aid kits', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(help_text='Player who commands this squad', on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='game.player')),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Member's name (e.g., 'SSG Thompson')", max_length=100)),
                ('rank', models.CharField(choices=[('staff_sergeant', 'Staff Sergeant (SSG)'), ('sergeant', 'Sergeant (SGT)'), ('specialist', 'Specialist (SPC)'), ('private_first_class', 'Private First Class (PFC)')], help_text='Military rank', max_length=50)),
                ('fire_team', models.CharField(choices=[('hq', 'Squad HQ'), ('alpha', 'Alpha Team'), ('bravo', 'Bravo Team')], help_text='Fire team assignment', max_length=20)),
                ('role', models.CharField(choices=[('squad_leader', 'Squad Leader'), ('team_leader', 'Team Leader'), ('automatic_rifleman', 'Automatic Rifleman'), ('grenadier', 'Grenadier'), ('rifleman', 'Rifleman')], help_text='Primary role in squad', max_length=30)),
                ('secondary_duty', models.CharField(blank=True, choices=[('', 'None'), ('medic', 'Medic'), ('engineer', 'Engineer'), ('talker', 'Talker (Linguist)')], help_text='Secondary specialty', max_length=20)),
                ('primary_weapon', models.CharField(choices=[('m4a1', 'M4A1 Carbine'), ('m4a1_m320', 'M4A1 with M320 Grenade Launcher'), ('m249', 'M249 Light Machine Gun')], help_text='Primary weapon', max_length=50)),
                ('health', models.IntegerField(default=100, help_text='Current health', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_health', models.IntegerField(default=100, help_text='Maximum health', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_alive', models.BooleanField(default=True, help_text='Whether member is alive')),
                ('is_wounded', models.BooleanField(default=False, help_text='Has injuries affecting performance')),
                ('is_suppressed', models.BooleanField(default=False, help_text='Currently suppressed by enemy fire')),
                ('strength', models.IntegerField(default=10, help_text='Physical power', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.IntegerField(default=10, help_text='Agility and accuracy', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('constitution', models.IntegerField(default=10, help_text='Endurance and toughness', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('intelligence', models.IntegerField(default=10, help_text='Tactical awareness', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('marksmanship', models.IntegerField(default=50, help_text='Shooting accuracy', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('melee_combat', models.IntegerField(default=30, help_text='Close quarters combat', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('explosives', models.IntegerField(default=20, help_text='Explosives and demolitions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medical', models.IntegerField(default=10, help_text='Medical treatment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('engineering', models.IntegerField(default=10, help_text='Repairs and fortifications', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tactics', models.IntegerField(default=30, help_text='Tactical decision making', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kills', models.IntegerField(default=0, help_text='Confirmed kills', validators=[django.core.validators.MinValueValidator(0)])),
                ('shots_fired', models.IntegerField(default=0, help_text='Total shots fired', validators=[django.core.validators.MinValueValidator(0)])),
                ('experience', models.IntegerField(default=0, help_text='Combat experience points', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('squad', models.ForeignKey(help_text='Squad this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.squad')),
            ],
            options={
                'verbose_name': 'Squad Member',
                'verbose_name_plural': 'Squad Members',
                'ordering': ['fire_team', 'role'],
                'indexes': [models.Index(fields=['squad', 'fire_team'], name='game_squadm_squad_i_5551b7_idx'), models.Index(fields=['is_alive'], name='game_squadm_is_aliv_f588a3_idx')],
            },
        ),
    ]
