# Generated by Django 4.2.26 on 2025-12-01 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_squad_squadmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mission_type', models.CharField(choices=[('recon', 'Reconnaissance'), ('raid', 'Raid'), ('rescue', 'Rescue'), ('escort', 'Escort'), ('assassination', 'Assassination'), ('defense', 'Defense'), ('patrol', 'Patrol'), ('investigation', 'Investigation'), ('diplomatic', 'Diplomatic'), ('scavenge', 'Scavenging'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Public missions affect server state and award XP/assets. Private missions are personal narratives.')),
                ('difficulty', models.CharField(choices=[('trivial', 'Trivial'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('very_hard', 'Very Hard'), ('extreme', 'Extreme'), ('impossible', 'Impossible')], default='moderate', max_length=20)),
                ('required_level', models.IntegerField(default=1)),
                ('required_squad_size', models.IntegerField(default=1, help_text='Minimum squad members required')),
                ('target_location_description', models.TextField(blank=True, help_text="Description of where the mission takes place (e.g., 'Grid reference 437-862')")),
                ('hook_title', models.CharField(help_text='Compelling hook title', max_length=200)),
                ('hook_description', models.TextField(help_text='Opening scene that hooks the player')),
                ('act1_title', models.CharField(default='Setup', max_length=200)),
                ('act1_description', models.TextField(help_text='Setup and rising action')),
                ('act1_objectives', models.JSONField(default=list, help_text="List of objectives for Act 1: [{'key': 'obj1', 'description': '...', 'required': true}]")),
                ('act2_title', models.CharField(default='Confrontation', max_length=200)),
                ('act2_description', models.TextField(help_text='Main conflict and complications')),
                ('act2_objectives', models.JSONField(default=list, help_text='List of objectives for Act 2')),
                ('act3_title', models.CharField(default='Climax', max_length=200)),
                ('act3_description', models.TextField(help_text='Climactic confrontation')),
                ('act3_objectives', models.JSONField(default=list, help_text='List of objectives for Act 3')),
                ('conclusion_success', models.TextField(help_text='Satisfying conclusion if mission succeeds')),
                ('conclusion_failure', models.TextField(blank=True, help_text='Conclusion if mission fails')),
                ('conclusion_partial', models.TextField(blank=True, help_text='Conclusion if mission partially succeeds')),
                ('reward_xp', models.IntegerField(default=0, help_text='XP awarded (public missions only)')),
                ('reward_currency', models.IntegerField(default=0, help_text='Currency awarded')),
                ('reward_items', models.JSONField(default=list, help_text="Items awarded: [{'item_key': 'key', 'quantity': 1}]")),
                ('reward_reputation', models.JSONField(default=dict, help_text="Reputation changes: {'faction_key': amount}")),
                ('failure_consequences', models.JSONField(default=dict, help_text="Server state changes on failure (public missions only): {'type': 'consequence_data'}")),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('can_fail', models.BooleanField(default=True)),
                ('can_abandon', models.BooleanField(default=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('cooldown_hours', models.IntegerField(default=0, help_text='Hours before mission can be repeated')),
                ('required_missions_completed', models.JSONField(default=list, help_text='Mission keys that must be completed first')),
                ('required_items', models.JSONField(default=list, help_text="Items required to start: [{'item_key': 'key', 'quantity': 1, 'consumed': false}]")),
                ('enemy_spawns', models.JSONField(default=list, help_text="Enemies to spawn: [{'npc_key': 'key', 'location': 'desc', 'act': 1, 'optional': false}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Can this mission be started?')),
                ('given_by_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_given', to='game.npc')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_starting_here', to='game.room')),
            ],
            options={
                'ordering': ['required_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mission_type', models.CharField(choices=[('recon', 'Reconnaissance'), ('raid', 'Raid'), ('rescue', 'Rescue'), ('escort', 'Escort'), ('assassination', 'Assassination'), ('defense', 'Defense'), ('patrol', 'Patrol'), ('investigation', 'Investigation'), ('diplomatic', 'Diplomatic'), ('scavenge', 'Scavenging'), ('custom', 'Custom')], max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('template_data', models.JSONField(default=dict, help_text='Template with variables: {{enemy_type}}, {{location}}, etc.')),
                ('variable_options', models.JSONField(default=dict, help_text="Options for each variable: {'enemy_type': ['orcs', 'wizards'], ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MissionDialogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act', models.IntegerField(choices=[(1, 'Act 1'), (2, 'Act 2'), (3, 'Act 3'), (0, 'Hook')])),
                ('trigger_point', models.CharField(help_text="When to show: 'start', 'end', 'objective_complete', etc.", max_length=50)),
                ('speaker_name', models.CharField(help_text="Override speaker name (e.g., 'Unknown Voice')", max_length=100)),
                ('dialogue_tree', models.JSONField(default=dict, help_text='Dialogue tree structure with branches')),
                ('sequence_order', models.IntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='game.mission')),
                ('speaker_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.npc')),
            ],
            options={
                'ordering': ['mission', 'act', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='available', max_length=20)),
                ('current_act', models.IntegerField(default=0, help_text='0=Hook, 1=Act1, 2=Act2, 3=Act3, 4=Complete')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_expires', models.DateTimeField(blank=True, null=True)),
                ('objectives_completed', models.JSONField(default=dict, help_text="Track objective completion: {'act1_obj1': true, 'act2_obj1': false, ...}")),
                ('events_triggered', models.JSONField(default=list, help_text='List of event keys that have been triggered')),
                ('choices_made', models.JSONField(default=list, help_text="List of choices made: [{'event_key': 'key', 'choice': 'text', 'outcome': 'key'}]")),
                ('mission_variables', models.JSONField(default=dict, help_text="Mission-specific variables: {'enemy_count': 5, 'hostages_saved': 2, ...}")),
                ('success_level', models.CharField(blank=True, choices=[('full', 'Full Success'), ('partial', 'Partial Success'), ('failure', 'Failure')], max_length=20, null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes about how mission concluded')),
                ('rewards_claimed', models.BooleanField(default=False)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('currency_awarded', models.IntegerField(default=0)),
                ('items_awarded', models.JSONField(default=list)),
                ('squad_snapshot', models.JSONField(default=dict, help_text='Snapshot of squad at mission start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_instances', to='game.mission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='game.player')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['player', 'status'], name='game_player_player__86275c_idx'), models.Index(fields=['mission', 'status'], name='game_player_mission_58b35c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('dialogue', 'Dialogue'), ('combat', 'Combat Encounter'), ('choice', 'Player Choice'), ('discovery', 'Discovery'), ('ambush', 'Ambush'), ('reinforcements', 'Reinforcements'), ('betrayal', 'Betrayal'), ('rescue', 'Rescue'), ('custom', 'Custom Event')], max_length=20)),
                ('act', models.IntegerField(choices=[(1, 'Act 1'), (2, 'Act 2'), (3, 'Act 3')])),
                ('trigger_type', models.CharField(choices=[('objective_complete', 'When objective completed'), ('location_enter', 'When entering location'), ('time_elapsed', 'After time elapsed'), ('health_threshold', 'When health drops below threshold'), ('enemy_killed', 'When specific enemy killed'), ('item_acquired', 'When item acquired'), ('random', 'Random chance'), ('manual', 'Manually triggered')], max_length=30)),
                ('trigger_conditions', models.JSONField(default=dict, help_text="Conditions for triggering: {'objective_key': 'obj1', 'threshold': 50, ...}")),
                ('trigger_chance', models.FloatField(default=1.0, help_text='Probability of triggering (0.0 to 1.0)')),
                ('description', models.TextField(help_text='What happens in this event')),
                ('choices', models.JSONField(default=list, help_text="Player choices: [{'text': 'Choice text', 'outcome': 'outcome_key', 'requirements': {}}]")),
                ('outcomes', models.JSONField(default=dict, help_text="Outcomes by outcome_key: {'outcome1': {'description': '...', 'effects': {...}}}")),
                ('is_repeatable', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.mission')),
            ],
            options={
                'ordering': ['mission', 'act', 'name'],
                'unique_together': {('mission', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['key'], name='game_missio_key_105f74_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_public', 'is_active'], name='game_missio_is_publ_f92800_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['mission_type'], name='game_missio_mission_683011_idx'),
        ),
    ]
